{% set version = "4.5.0" %}

package:
  name: jupyter_core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_core/jupyter_core-{{ version }}.tar.gz
  sha256: 2c6e7c1e9f2ac45b5c2ceea5730bc9008d92fe59d0725eac57b04c0edfba24f7

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  entry_points:
    - jupyter = jupyter_core.command:main
    - jupyter-migrate = jupyter_core.migrate:main
    - jupyter-troubleshoot = jupyter_core.troubleshoot:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - traitlets

test:
  commands:
    - jupyter -h
    - jupyter-migrate -h
    - jupyter-troubleshoot --help
  imports:
    - jupyter_core
    - jupyter_core.utils

about:
  home: http://jupyter.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: Core common functionality of Jupyter projects.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - ocefpaf
