{% set version = "4.3.0" %}

package:
  name: jupyter_core
  version: {{ version }}

source:
  fn: jupyter_core-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyter_core/jupyter_core-{{ version }}.tar.gz
  sha256: a96b129e1641425bf057c3d46f4f44adce747a7d60107e8ad771045c36514d40

build:
  number: 0
  script: pip install --no-deps .
  entry_points:
    - jupyter = jupyter_core.command:main
    - jupyter-migrate = jupyter_core.migrate:main
    - jupyter-troubleshoot = jupyter_core.troubleshoot:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - traitlets

test:
  commands:
    - jupyter -h
    - jupyter-migrate -h
    - jupyter-troubleshoot --help
  imports:
    - jupyter_core
    - jupyter_core.utils

about:
  home: http://jupyter.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: Core common functionality of Jupyter projects.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - ocefpaf
