{% set version = "4.1.1" %}

package:
  name: jupyter_core
  version: {{ version }}

source:
  fn: jupyter_core-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyter_core/jupyter_core-{{ version }}.tar.gz
  sha256: ae0e69435258126466c86cd989e465a9c334c50107ef4f257decc8693650bf4c

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
  run:
    - python
    - traitlets

test:
  commands:
    - jupyter -h
    - jupyter-migrate -h
    - jupyter-troubleshoot --help
  imports:
    - jupyter_core
    - jupyter_core.utils

about:
  home: http://jupyter.org
  license: BSD 3-clause
  summary: Core common functionality of Jupyter projects.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - ocefpaf
