travis:
  secure:
    BINSTAR_TOKEN: PlWjFJHKGtYbdu76wEZVABii7DQn8pCiCGhuQL0vb40hjlDZAK6+C3MGsMDV19/hrDnCQUeeHcg6RjLpSHannRhykWVQptwLrZNXNwqVvS+qJxvrQlEcIz4k0jS7i51iTtApJuhSvly7o8rN2vqwNx54ayx890Zs/nr0NZjjjqv6oGPn2ghChb0qZTw5B1XeksuJt/6KIVztvPIdTNgnCn3sV82DouQcKRZaGx3kn7/XVPbHbsT0BC1cgv+K+PfhxhkB5jMHSUogCPrtxgAGn9Rl6oWlZAOpZ2JIabEFd8Jt3MCUCe/8/qa8ESIrHYbT3MOlrFU/d/Utt6Z3Ms+npUyIRvcYegnlLcG6TE/BXPn47/smY8Xf5BYGelPfNLRUjQJzJ7F4xsAI5okS6L2NTx/KvDOVP4ILHVOgnJ/6jdPL+bfd7vnft99OEwEfEcfn+FNmvWUxZsn2dB7fVUjTrJKNiS9zEBY+Je+Oi6N8YZhWj5C3WHsgT4hCuqLCybfoRcmgLUBhqqH/o3WYtZZ1CsIbzaKjwXyeRzoXh0LA4MlKT0qJvT05npvimKTdWzhdmCagFv2q3BPLa3U2RPTPdWDF0450Q5uxgWUe0BQJG5WyNEneUIXQf2/5sIOz7nFy5iPxnl00KJkw3mknbQ/nurls9KfCpxOzMRrGN1kmzwo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
